default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: newpassword
  host: localhost
  port: 5432

development:
  <<: *default
  database: word_wise_development

test:
  <<: *default
  database: word_wise_test

production:
  <<: *default
  database: word_wise_production
  username: word_wise
  password: <%= ENV["WORD_WISE_DATABASE_PASSWORD"] %>
